const $=id=>document.getElementById(id);
const ui={connect:$('connect'),audio:$('audio'),status:$('status'),device:$('device'),led:$('led'),level:$('level'),cc:$('cc-value'),ccMeter:$('cc-meter'),freq:$('freq'),freqMeter:$('freq-meter'),sensitivity:$('sensitivity'),sensOut:$('sens-out'),scale:$('scale'),planet:$('planet'),canvas:$('cosmos')};
const ctx=ui.canvas.getContext('2d',{alpha:true});
let midi=null,input=null,audio=null,osc=null,gain=null,filter=null,started=false,raw=0,smoothed=0,ccNumber=null,lastTouch=0,raf=0;
const scales=[[0,2,4,7,9],[0,2,3,5,7,9,10],Array.from({length:12},(_,i)=>i)];
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
function resize(){const d=Math.min(devicePixelRatio||1,2);ui.canvas.width=Math.floor(innerWidth*d);ui.canvas.height=Math.floor(innerHeight*d);ctx.setTransform(d,0,0,d,0,0)}
addEventListener('resize',resize,{passive:true});resize();
function noteFrequency(value){const root=36,scale=scales[Number(ui.scale.value)],octaves=3,steps=scale.length*octaves,index=Math.round(clamp(value)*Math.max(0,steps-1)),semi=scale[index%scale.length]+12*Math.floor(index/scale.length);return 440*Math.pow(2,(root+semi-69)/12)}
function update(value,cc){raw=clamp(value);smoothed+=(raw-smoothed)*.22;lastTouch=performance.now();ccNumber=cc;const pct=Math.round(smoothed*100),hz=noteFrequency(smoothed);ui.level.innerHTML=pct+'<span>%</span>';ui.cc.textContent=cc===null?'—':String(cc).padStart(3,'0');ui.ccMeter.style.width=(smoothed*100)+'%';ui.freq.textContent=Math.round(hz)+' Hz';ui.freqMeter.style.width=(clamp((hz-60)/700)*100)+'%';ui.planet.style.filter='brightness('+(1+smoothed*.65)+') saturate('+(1+smoothed*.8)+')';ui.planet.style.transform='scale('+(1+smoothed*.07)+')';if(gain&&started){osc.frequency.setTargetAtTime(hz,audio.currentTime,.035);filter.frequency.setTargetAtTime(450+smoothed*5000,audio.currentTime,.04);gain.gain.setTargetAtTime(.025+smoothed*.16,audio.currentTime,.05)}ui.led.classList.toggle('on',smoothed>.015)}
function handleMidi(e){const [status,data,value]=e.data;const type=status&0xf0;if(type===0xb0){const normalized=value/127;update(normalized,data)}else if(type===0x90){update(value/127, data)}else if(type===0x80){update(0,data)}}
async function connect(){if(!navigator.requestMIDIAccess){ui.status.textContent='WEB MIDI INDISPONIBLE';return}ui.status.textContent='RECHERCHE MIDI…';try{midi=await navigator.requestMIDIAccess();refresh();midi.onstatechange=refresh;if(!input)ui.status.textContent='TOUCHEZ LE CAPTEUR POUR IDENTIFIER LE SIGNAL'}catch(e){ui.status.textContent=e.name==='NotAllowedError'?'ACCÈS MIDI REFUSÉ':'MIDI INDISPONIBLE';console.error(e)}}
function refresh(){const ports=[...midi.inputs.values()];if(input)input.onmidimessage=null;input=ports.find(p=>/touch|playtron|playtronica/i.test(p.name))||ports[0]||null;if(input){input.onmidimessage=handleMidi;ui.device.textContent=input.name.toUpperCase();ui.status.textContent='CAPTEUR CONNECTÉ · EN ATTENTE';ui.led.classList.add('on')}else{ui.device.textContent='AUCUN APPAREIL';ui.status.textContent='CONNECTEZ LE TOUCHME';ui.led.classList.remove('on')}}
async function enableAudio(){if(started){audio.resume();return}const AC=window.AudioContext||window.webkitAudioContext;if(!AC){ui.status.textContent='WEB AUDIO INDISPONIBLE';return}audio=new AC();osc=audio.createOscillator();gain=audio.createGain();filter=audio.createBiquadFilter();osc.type='sine';osc.frequency.value=110;filter.type='lowpass';filter.frequency.value=1200;gain.gain.value=0;osc.connect(filter).connect(gain).connect(audio.destination);osc.start();started=true;ui.audio.textContent='AUDIO ACTIVÉ';ui.status.textContent=input?'CAPTEUR CONNECTÉ · AUDIO ACTIF':'AUDIO ACTIF · CONNECTEZ LE CAPTEUR'}
ui.connect.addEventListener('click',connect);ui.audio.addEventListener('click',enableAudio);ui.sensitivity.addEventListener('input',()=>{ui.sensOut.textContent=Number(ui.sensitivity.value).toFixed(1)+'×'});ui.scale.addEventListener('change',()=>update(smoothed,ccNumber));
let particles=Array.from({length:95},()=>({x:Math.random(),y:Math.random(),r:.3+Math.random()*1.2,p:Math.random()*6.28,s:.15+Math.random()*.5}));
function draw(t){const w=innerWidth,h=innerHeight;ctx.clearRect(0,0,w,h);const strength=smoothed;for(const p of particles){p.p+=.003*p.s;const drift=Math.sin(p.p+t*.00015)*.008;const x=(p.x+drift+1)%1*w,y=(p.y+Math.cos(p.p+t*.00012)*.012+1)%1*h;ctx.beginPath();ctx.arc(x,y,p.r+strength*1.3,0,Math.PI*2);ctx.fillStyle='rgba(174,190,255,'+(.12+strength*.42)+')';ctx.fill()}if(performance.now()-lastTouch>180){smoothed*=.985;if(smoothed<.002)smoothed=0;update(smoothed,ccNumber)}raf=requestAnimationFrame(draw)}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&gain&&audio)gain.gain.setTargetAtTime(0,audio.currentTime,.03)});draw(0);